"""
Fortran-lang webpage configuration file.

This configuration file is for the Sphinx documentation builder.

For information on the format, see
https://www.sphinx-doc.org/en/master/usage/configuration.html
"""

# -- Imports -----------------------------------------------------------------

from jinja2 import Environment, FileSystemLoader
import json
import os
import pathlib
import re
import sys
import yaml

# Project-specific imports
root = pathlib.Path(__file__).parent.parent
sys.path.insert(0, str(root / "extensions"))
sys.path.insert(0, str(root.absolute()))
from fortran_package import update_json_files


# -- Project information -----------------------------------------------------

project = "Fortran-lang.org website"
copyright = "2020-2026, Fortran Community"
author = "Fortran Community"

# The full version, including alpha/beta/rc tags
release = "1.0.0"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "ablog",
    "myst_parser",
    "sphinx_design",
    "sphinx_copybutton",
    "sphinx.ext.intersphinx",
    "sphinx_jinja",
    "fortran_playground",
    "sphinx_favicon",
    "sphinx_tags",
]

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "substitution",
    "dollarmath",
    "html_image",
]
myst_heading_anchors = 3


# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]
locale_dirs = ["../locale/"]
# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.

language = str(sys.argv[-1][11:])
html_search_language = str(sys.argv[-1][11:])

if language == "en":
    extensions.append("sphinx_sitemap")

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["learn/intrinsics/_pages/*.md"]
html_additional_pages = {}
suppress_warnings = ["myst.header"]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "pydata_sphinx_theme"
html_show_sourcelink = False

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = ["custom.css"]
html_canonical_url = None

favicons = [
    {
        "rel": "icon",
        "sizes": "256x256",
        "href": "images/favicon.ico",
    },
]

html_theme_options = {
    "show_prev_next": False,
    "show_nav_level": 1,
    "show_toc_level": 0,
    "navbar_align": "right",
    "navbar_start": ["navbar-logo", "theme-switcher.html"],
    "switcher": {
        "json_url": "https://fortran-lang.org/_static/data.json",  # shifted to custom local switcher
        "version_match": language,
    },
    "primary_sidebar_end": [],
    "secondary_sidebar_items": ["inpage_toc.html"],
    "navbar_end": ["navbar-icon-links", "version-switcher"],
    "search_bar_text": "Search",
    "icon_links": [
        {
            "name": "Discourse",
            "url": "https://fortran-lang.discourse.group/",
            "icon": "fab fa-discourse",
        },
        {
            "name": "Twitter",
            "url": "https://twitter.com/fortranlang",
            "icon": "fab fa-twitter",
        },
        {
            "name": "GitHub",
            "url": "https://github.com/fortran-lang",
            "icon": "fab fa-github",
        },
        {
            "name": "RSS",
            "url": "https://fortran-lang.org/news/atom.xml",
            "icon": "fas fa-rss",
        },
    ],
}

html_sidebars = {
    "news": [
        "ablog/tagcloud.html",
        "ablog/archives.html",
        "ablog/recentposts.html",
    ],
    "news/**": [
        "ablog/postcard.html",
        "ablog/recentposts.html",
        "ablog/archives.html",
    ],
    "learn/**": ["sidebar-nav-bs.html"],
    "learn": [],
    "index": ["index_sidebar.html"],
    "compilers": [],
    "packages": [],
    "community": [],
    "packages/**": [],
    "community/governance": [],
}
html_title = "Fortran Programming Language"
html_logo = "_static/images/fortran-logo-256x256.png"

master_doc = "index"

fontawesome_link_cdn = True

blog_path = "news"
blog_post_pattern = "news/**"
blog_baseurl = "https://fortran-lang.org"
html_baseurl = "https://fortran-lang.org"
sitemap_url_scheme = "{link}"
post_redirect_refresh = 1
post_auto_image = 1
post_auto_excerpt = 2

gettext_compact = "index"

copybutton_exclude = ".linenos, .gp, .go"

## tag handling
tags_create_tags = True
tags_create_badges = True
tags_extension = ["md"]
tags_page_title = "Tags"
tags_page_header = "Packages with this tag"


# -- Load jinja contexts from file -------------------------------------------

data_files = {
    "fortran-learn": pathlib.Path(root, "_data", "fortran_learn.json"),
    "fortran-packages": pathlib.Path(root, "_data", "fortran_package.json"),
    "fortran-tags": pathlib.Path(root, "_data", "fortran_tags.json"),
    "contributors": pathlib.Path(root, "_data", "contributor.json"),
    "package-index": pathlib.Path(root, "data", "package_index.yml"),
    "fortran-categories": pathlib.Path(root, "data", "categories.yml"),
    "intrinsics": pathlib.Path(root, "data", "intrinsics.yml"),
}

# Regenerate data files if required
if not all(data.exists() for data in data_files.values()):
    update_json_files()

# Read data from the files that were generated above if not already present
with open(data_files["fortran-learn"], "r", encoding="utf-8") as f:
    conf = json.load(f)
with open(data_files["fortran-packages"], "r", encoding="utf-8") as f:
    fortran_packages = json.load(f)
with open(data_files["fortran-tags"], "r", encoding="utf-8") as f:
    fortran_tags = json.load(f)
with open(data_files["contributors"], "r", encoding="utf-8") as f:
    contributors = json.load(f)
with open(data_files["fortran-categories"], "r", encoding="utf-8") as f:
    fortran_categories = yaml.safe_load(f)
with open(data_files["intrinsics"], "r", encoding="utf-8") as f:
    intrinsics = yaml.safe_load(f)
with open(data_files["package-index"], "r", encoding="utf-8") as f:
    package_index = yaml.safe_load(f)

jinja_contexts = {
    "conf": conf,
    "fortran_index": fortran_packages,
    "tags": fortran_tags,
    "categories": {"categories": fortran_categories},
    "contributors": contributors,
    "intrinsics": intrinsics,
}


def generate_package_pages(app, config):
    """Generate per-package pages from templates."""
    loader = FileSystemLoader(app.srcdir)
    env = Environment(loader=loader)

    # Configure packages
    template_path = os.path.join("_templates/package.md")
    out_dir = os.path.join(app.srcdir, "packages")
    os.makedirs(out_dir, exist_ok=True)
    template = env.get_template(template_path)

    # Auto-generate the package pages
    for package in package_index:
        content = template.render(package=package)
        stub = re.sub(r"[^a-z0-9]+", "-", package["name"].lower()).strip("-")
        with open(os.path.join(out_dir, f"{stub}.md"), "w") as f:
            f.write(content)


def generate_category_pages(app, config):
    """Generate per-category and tag pages from templates."""
    loader = FileSystemLoader(app.srcdir)
    env = Environment(loader=loader)

    # Configure categories
    template_path = os.path.join("_templates/category_pages.md")
    out_dir = os.path.join(app.srcdir, "categories")
    os.makedirs(out_dir, exist_ok=True)
    template = env.get_template(template_path)

    # Auto-generate the category pages
    for tag in fortran_packages.keys():
        content = template.render(
            title=fortran_categories[tag]["title"],
            description=fortran_categories[tag]["description"],
            items=fortran_packages[tag],
        )

        # Auto-generate tag pages
        with open(os.path.join(out_dir, f"{tag}.md"), "w") as f:
            f.write(content)


def setup(app):
    """Drive the Sphinx build."""

    # Tasks to run once config has been initialised
    app.connect("config-inited", generate_package_pages)
    app.connect("config-inited", generate_category_pages)
